# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [2]:
import numpy as np

In [10]:
## 1

arr = np.random.randint(1, 20, size=(5,5))
print(arr)

arr[:,2] = 1
print(arr)


[[15  1  9 15  2]
 [ 5 13 10  6 10]
 [ 5 19 10  1  4]
 [ 2  6  5 10 11]
 [ 6  4 11 13 14]]
[[15  1  1 15  2]
 [ 5 13  1  6 10]
 [ 5 19  1  1  4]
 [ 2  6  1 10 11]
 [ 6  4  1 13 14]]


In [15]:
## 2

arr = np.random.randint(1, 16, size=(4,4))

np.fill_diagonal(arr,0)
print(arr)

[[ 0 12 10 15]
 [ 3  0  9  6]
 [ 7 13  0  3]
 [ 4  9  6  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [ ]:
## 1

arr = np.random.randint(1, 36, size=(6,6))

print(arr)


[[ 3  3 11  4 24 27]
 [21 10  6  4 34 12]
 [11 20 22 16 30 27]
 [17  6  3  6  2 27]
 [ 6 28 19 29 31 35]
 [32 12 13 18 20 33]]


In [20]:
arr[2:4,1:3]


array([[20, 22],
       [ 6,  3]], dtype=int32)

In [27]:
## 2
arr = np.random.randint(1, 36, size=(5,5))
print(arr)


top = arr[0,:]
print("top",top)

bot = arr[4,:]
print("bot",bot)

left = arr[:,0]
print("left",left)

right = arr[:,4]
print("right",right)

[[13  3 32 19 35]
 [33 10  5 15  5]
 [21 16 23 22 20]
 [10 18 16 15  4]
 [33 22 22 13 10]]
top [13  3 32 19 35]
bot [33 22 22 13 10]
left [13 33 21 10 33]
right [35  5 20  4 10]


In [32]:
np.concatenate((top, bot, left, right),axis=0)

array([13,  3, 32, 19, 35, 33, 22, 22, 13, 10, 13, 33, 21, 10, 33, 35,  5,
       20,  4, 10], dtype=int32)

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [34]:
## 1

arr1 = np.random.randint(1, 36, size=(3,4))
print(arr1)

arr2 = np.random.randint(1, 36, size=(3,4))
print(arr2)

print("add",arr1 + arr2)
print("sub",arr1 - arr2)
print("mul",arr1 * arr2)
print("div",arr1 / arr2)

[[ 4  1 30 35]
 [20 13 11 34]
 [10 32 22 25]]
[[25 30 22 33]
 [20  8 15 29]
 [17  9 19 26]]
add [[29 31 52 68]
 [40 21 26 63]
 [27 41 41 51]]
sub [[-21 -29   8   2]
 [  0   5  -4   5]
 [ -7  23   3  -1]]
mul [[ 100   30  660 1155]
 [ 400  104  165  986]
 [ 170  288  418  650]]
div [[0.16       0.03333333 1.36363636 1.06060606]
 [1.         1.625      0.73333333 1.17241379]
 [0.58823529 3.55555556 1.15789474 0.96153846]]


In [39]:
## 2

arr = np.random.randint(1, 16, size=(4,4))
print(arr)

print("row-wise sum", np.sum(arr, axis=1))
print("column-wise sum", np.sum(arr, axis=0))

[[10  9 10 14]
 [12  8 11  9]
 [ 7 12 11 10]
 [ 7 10 14  6]]
row-wise sum [43 40 40 37]
column-wise sum [36 39 46 39]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).


In [41]:
## 1

arr = np.random.randint(1, 36, size=(5,5))
print(arr)

print("mean", np.mean(arr))
print("meadian", np.median(arr))
print("std", np.std(arr))
print("var", np.var(arr))

[[27 25 13 25 24]
 [29 20  6  9 16]
 [23  7 23 22 21]
 [22 34  6 33 29]
 [32 14  2 10 15]]
mean 19.48
meadian 22.0
std 9.029374286183955
var 81.52960000000002


In [44]:
## 2

arr = np.random.randint(1, 16, size=(3,3))
print(arr)

mean = np.mean(arr)
std = np.std(arr)

normalized_arr = (arr - mean) / std
print("Normalized array:")

[[ 1  3  4]
 [14  6  8]
 [12 15  4]]
Normalized array:


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [48]:
## 1

arr = np.random.randint(1, 36, size=(3,3))
## 1
print(arr)

## 1

row_arr = np.random.randint(1, 36, size=(3,))
print("Row array:", row_arr)

result = arr + row_arr
print("Result after adding row array:", result)

[[ 8 14 12]
 [ 6 30  8]
 [10 11  8]]
Row array: [29 17  6]
Result after adding row array: [[37 31 18]
 [35 47 14]
 [39 28 14]]


In [50]:
## 2

arr = np.random.randint(1, 36, size=(4,4))
print(arr)


row_arr = np.random.randint(1, 36, size=(4,))
print("Row array:", row_arr)

[[ 4  2 12 19]
 [27 12 27 21]
 [12  3 29  7]
 [32 35 19 25]]
Row array: [19 16  6 24]


In [55]:
row_arr[:, np.newaxis]

array([[19],
       [16],
       [ 6],
       [24]], dtype=int32)

In [ ]:
result = arr - row_arr[:, np.newaxis]
print("Result after subtract columns array:", result)

Result after adding row array: [[-15 -17  -7   0]
 [ 11  -4  11   5]
 [  6  -3  23   1]
 [  8  11  -5   1]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [57]:
## 1
arr = np.random.randint(1, 20, size=(3,3))
print(arr)

print("derivative", np.linalg.det(arr))
print("inverse", np.linalg.inv(arr))
print("transpose", np.linalg.eigvals(arr))

[[ 9 18 16]
 [ 8 18 16]
 [17  8 15]]
derivative 142.0000000000005
inverse [[ 1.00000000e+00 -1.00000000e+00  2.87351842e-16]
 [ 1.07042254e+00 -9.64788732e-01 -1.12676056e-01]
 [-1.70422535e+00  1.64788732e+00  1.26760563e-01]]
transpose [41.52850064+0.j          0.23574968+1.83405577j  0.23574968-1.83405577j]


In [64]:
## 2

arr1 = np.random.randint(1, 20, size=(2,3))
print(arr1)

arr2 = np.random.randint(1, 20, size=(3,2))
print(arr2)

print("matrix multiplication", np.dot(arr1, arr2))

[[ 6 13  9]
 [ 9  3  7]]
[[13 11]
 [18  5]
 [10 10]]
matrix multiplication [[402 221]
 [241 184]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [66]:
## 1
arr = np.random.randint(1, 9, size=(3,3))
print(arr)

print("reshape", arr.reshape(1,9))
print("reshape", arr.reshape(9,1))

[[3 3 2]
 [2 6 5]
 [3 3 4]]
reshape [[3 3 2 2 6 5 3 3 4]]
reshape [[3]
 [3]
 [2]
 [2]
 [6]
 [5]
 [3]
 [3]
 [4]]


In [79]:
## 2
arr = np.random.randint(1, 21, size=(5,5))
print(arr)

flattened_arr = arr.flatten()
print("flatten", flattened_arr)

# Reshape the array back to (5, 5)
reshaped_array = flattened_arr.reshape((5, 5))
print("Reshaped array:")
print(reshaped_array)

[[ 5  4 14  4 12]
 [20 13  5 20  2]
 [ 8  3 14 13 10]
 [ 6  3  2 19  3]
 [17  5  7  2  7]]
flatten [ 5  4 14  4 12 20 13  5 20  2  8  3 14 13 10  6  3  2 19  3 17  5  7  2
  7]
Reshaped array:
[[ 5  4 14  4 12]
 [20 13  5 20  2]
 [ 8  3 14 13 10]
 [ 6  3  2 19  3]
 [17  5  7  2  7]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [ ]:
# Top-Left → arr[0, 0] → 6

# Top-Right → arr[0, 4] → 1

# Bottom-Left → arr[4, 0] → 15

# Bottom-Right → arr[4, 4] → 1

In [88]:
## 1
arr = np.random.randint(1, 21, size=(5,5))
print(arr)

corner_indices = ([0, 0, 4, 4], [0, 4, 0, 4])

print("corner_indices",arr[corner_indices])

[[ 6 17 19 19  1]
 [15  2 12 10  2]
 [ 1  1 14 17  8]
 [14 15 11  2 17]
 [15  6  1 18  1]]
corner_indices [ 6  1 15  1]


In [85]:
## 2
arr = np.random.randint(1, 21, size=(4,4))
print(arr)

arr[arr > 10] = 10
print(arr)


[[18 17  5 17]
 [16 15  3 13]
 [ 9 14 13  1]
 [13  8  1 12]]
[[10 10  5 10]
 [10 10  3 10]
 [ 9 10 10  1]
 [10  8  1 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.


In [ ]:
### 1

data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


In [ ]:
#### 2

data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [100]:
## 1
import numpy.ma as ma  # ma = masked array module

arr = np.random.randint(1, 21, size=(5,5))
print(arr)

new_arr = ma.masked_greater(arr, 10)
print("Elements greater than 10:", new_arr)

print("Unmasked elements:", new_arr.sum())

[[13  1 16 20 20]
 [ 2 14 20  3 17]
 [ 4 16 12 12 10]
 [ 1  5  1 15  2]
 [13 11  9 14 20]]
Elements greater than 10: [[-- 1 -- -- --]
 [2 -- -- 3 --]
 [4 -- -- -- 10]
 [1 5 1 -- 2]
 [-- -- 9 -- --]]
Unmasked elements: 38


In [101]:
## 2

array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[15 14  8]
 [10 17 17]
 [ 1 12  7]]
Masked array:
[[-- 14 8]
 [10 -- 17]
 [1 12 --]]
Modified masked array:
[[10 14  8]
 [10 10 17]
 [ 1 12 10]]
